on:
  push:
    # tags:
    # - 'v*'

name: Upload Release Asset

jobs:
  get-package-version:
    name: Get Package Version on Linux

    runs-on: ubuntu-latest
    steps:
      - name: Extract version from package.json
        uses: sergeysova/jq-action@v2
        id: version
        run: echo "PACKAGE_VERSION=$(jq .version package.json -r)" >> $GITHUB_OUTPUT
